LISTS_OF_BLOCKED_WEBSITES = ["www.facebook.com", "facebook.com", 'youtube.com', 'www.youtube.com']
SPREADSHEET_ID = "1iV3yh3dGPy27lEUXfVMrnASVF8RTCBNVXTtxd3a4EtY"
WINDOWS_TITLE = "Pomodoro blocker"
PATH_TO_TOMATO_IMAGE = 'Images/tomato.png'
PATH_TO_SOUND = 'Sounds/Ting.wav'
PATH_TO_JSON = 'Json/pomodoro-logger.json'
SIZE_OF_WINDOW_GUI = "412x324"
SECONDS_IN_MINUTE = 60
LEARNING_MINUTES = 25 * SECONDS_IN_MINUTE
SHORT_BREAK_MINUTES = 5 * SECONDS_IN_MINUTE
LONG_BREAK_MINUTES = 10 * SECONDS_IN_MINUTE
NUMBER_OF_BREAKS = 4


